"""Campaign workflow backends."""

from pajin.workflow.campaign_profile import (
    CAMPAIGN_PROFILE_API_VERSION,
    CAMPAIGN_PROFILE_CATALOG_API_VERSION,
    CampaignProfileBenchmarkExpectation,
    CampaignProfileCatalog,
    CampaignProfileError,
    CampaignProfilePurpose,
    CampaignProfileReportingSemantics,
    RegisteredCampaignProfile,
    registered_campaign_profile_catalog,
    resolve_registered_campaign_profile,
)
from pajin.workflow.common_engine import (
    COMMON_CAMPAIGN_ENGINE_CONTRACT_API_VERSION,
    COMMON_CAMPAIGN_EXECUTION_PLAN_API_VERSION,
    CommonCampaignEngineContract,
    CommonCampaignExecutionPlanAuthority,
    plan_legacy_campaign_common_execution,
    registered_common_campaign_engine_contract,
)
from pajin.workflow.local import LocalCampaignRunner, RunOutcome
from pajin.workflow.profile_compatibility import (
    LEGACY_CAMPAIGN_PROFILE_COMPILATION_API_VERSION,
    LEGACY_CAMPAIGN_PROFILE_PROJECTION_API_VERSION,
    LEGACY_MODE_PROFILE_COMPILER_API_VERSION,
    CampaignProfileCompatibilityError,
    LegacyCampaignProfileCompilationAuthority,
    LegacyCampaignProfileProjection,
    LegacyModeProfileCompiler,
    LegacyModeProfileMapping,
    compile_legacy_campaign_profile,
    registered_legacy_mode_profile_compiler,
)

__all__ = [
    "CAMPAIGN_PROFILE_API_VERSION",
    "CAMPAIGN_PROFILE_CATALOG_API_VERSION",
    "COMMON_CAMPAIGN_ENGINE_CONTRACT_API_VERSION",
    "COMMON_CAMPAIGN_EXECUTION_PLAN_API_VERSION",
    "LEGACY_CAMPAIGN_PROFILE_COMPILATION_API_VERSION",
    "LEGACY_CAMPAIGN_PROFILE_PROJECTION_API_VERSION",
    "LEGACY_MODE_PROFILE_COMPILER_API_VERSION",
    "CampaignProfileBenchmarkExpectation",
    "CampaignProfileCatalog",
    "CampaignProfileCompatibilityError",
    "CampaignProfileError",
    "CampaignProfilePurpose",
    "CampaignProfileReportingSemantics",
    "CommonCampaignEngineContract",
    "CommonCampaignExecutionPlanAuthority",
    "LegacyCampaignProfileCompilationAuthority",
    "LegacyCampaignProfileProjection",
    "LegacyModeProfileCompiler",
    "LegacyModeProfileMapping",
    "LocalCampaignRunner",
    "RegisteredCampaignProfile",
    "RunOutcome",
    "compile_legacy_campaign_profile",
    "plan_legacy_campaign_common_execution",
    "registered_campaign_profile_catalog",
    "registered_common_campaign_engine_contract",
    "registered_legacy_mode_profile_compiler",
    "resolve_registered_campaign_profile",
]
