"""Structured collaboration projections derived from existing PAJIN authorities."""

from pajin.collaboration.artifacts import (
    MAX_SHARED_ARTIFACT_BYTES,
    SHARED_ARTIFACT_REF_API_VERSION,
    SharedArtifactRef,
    SharedArtifactRefError,
    create_shared_artifact_ref,
    verify_shared_artifact_ref,
)
from pajin.collaboration.handoff import (
    AGENT_HANDOFF_API_VERSION,
    AgentHandoffAuthority,
    AgentHandoffError,
    AgentHandoffProposal,
    AgentHandoffPurpose,
    HandoffAgentRef,
    HandoffTaskRef,
    SupervisorMediatedAgentHandoff,
    create_agent_handoff_proposal,
    handoff_agent_ref,
    handoff_task_ref,
)
from pajin.collaboration.snapshots import (
    COLLABORATION_SNAPSHOT_API_VERSION,
    MAX_COLLABORATION_ARTIFACTS,
    MAX_COLLABORATION_FACTS,
    CollaborationSnapshot,
    CollaborationSnapshotError,
    SharedArtifactSource,
    create_collaboration_snapshot,
    verify_collaboration_snapshot,
)
from pajin.collaboration.terminal_result import (
    TERMINAL_RESULT_HANDOFF_API_VERSION,
    TerminalResultHandoff,
    TerminalResultHandoffAuthority,
    TerminalResultHandoffError,
    TerminalResultStatus,
)
from pajin.collaboration.urgent_observation import (
    URGENT_OBSERVATION_FAST_GATE_API_VERSION,
    UrgentObservationDisposition,
    UrgentObservationFastGateAuthority,
    UrgentObservationFastGateDecision,
    UrgentObservationFastGateError,
    UrgentObservationFastGatePolicy,
    UrgentObservationType,
)

__all__ = [
    "AGENT_HANDOFF_API_VERSION",
    "COLLABORATION_SNAPSHOT_API_VERSION",
    "MAX_COLLABORATION_ARTIFACTS",
    "MAX_COLLABORATION_FACTS",
    "MAX_SHARED_ARTIFACT_BYTES",
    "SHARED_ARTIFACT_REF_API_VERSION",
    "TERMINAL_RESULT_HANDOFF_API_VERSION",
    "URGENT_OBSERVATION_FAST_GATE_API_VERSION",
    "AgentHandoffAuthority",
    "AgentHandoffError",
    "AgentHandoffProposal",
    "AgentHandoffPurpose",
    "CollaborationSnapshot",
    "CollaborationSnapshotError",
    "HandoffAgentRef",
    "HandoffTaskRef",
    "SharedArtifactRef",
    "SharedArtifactRefError",
    "SharedArtifactSource",
    "SupervisorMediatedAgentHandoff",
    "TerminalResultHandoff",
    "TerminalResultHandoffAuthority",
    "TerminalResultHandoffError",
    "TerminalResultStatus",
    "UrgentObservationDisposition",
    "UrgentObservationFastGateAuthority",
    "UrgentObservationFastGateDecision",
    "UrgentObservationFastGateError",
    "UrgentObservationFastGatePolicy",
    "UrgentObservationType",
    "create_agent_handoff_proposal",
    "create_collaboration_snapshot",
    "create_shared_artifact_ref",
    "handoff_agent_ref",
    "handoff_task_ref",
    "verify_collaboration_snapshot",
    "verify_shared_artifact_ref",
]
