"""Generate browser validation constants from the public measurement contracts."""

from __future__ import annotations

import json

from pajin.workflow import ai_measured_product_flow as ai
from pajin.workflow import network_measured_product_flow as network
from pajin.workflow.ai_measured_case_authority import registered_ai_measured_case_mapping
from pajin.workflow.network_measured_case_authority import registered_network_measured_case_mapping


def measured_product_browser_contract() -> str:
    values: dict[str, object] = {}
    ai_public = registered_ai_measured_case_mapping().public_authority
    network_public = registered_network_measured_case_mapping().public_authority
    for domain, public, case_refs, boundary, states, rationals, kind in (
        (
            "ai",
            ai_public,
            [
                item.reference().model_dump(mode="json", by_alias=True)
                for item in ai_public.public_registry.cases
            ],
            ai.AIMeasuredProductAuthorityBoundary(),
            ai._EXPECTED_CASE_STATES,
            ai._FIXED_RATIONALS,
            "AIMeasuredProduct",
        ),
        (
            "network",
            network_public,
            [
                item.reference().model_dump(mode="json", by_alias=True)
                for item in network_public.public_registry.cases
            ],
            network.NetworkMeasuredProductAuthorityBoundary(),
            network._EXPECTED_CASE_STATES,
            network._FIXED_RATIONALS,
            "NetworkMeasuredProduct",
        ),
    ):
        metrics = []
        for requirement in public.validation_floor_policy.requirements:
            material = requirement.model_dump(mode="json", by_alias=True)
            metrics.append(
                {
                    "binding": {
                        key: material[key]
                        for key in (
                            "metric",
                            "unit",
                            "applicability",
                            "notApplicableReason",
                            "comparison",
                        )
                    },
                    "rational": rationals.get(requirement.metric.metric_id),
                }
            )
        values[domain] = {
            "apiVersion": f"pajin.dev/{domain}-measured-product/v1alpha1",
            "kind": kind,
            "productPrefix": f"{domain}-measured-product_",
            "evaluationPrefix": (
                "ai-replay-floor-evaluation_" if domain == "ai" else "network-replay-floor_"
            ),
            "cases": [
                {
                    "case": case,
                    "comparisonState": state,
                }
                for case, state in zip(case_refs, states, strict=True)
            ],
            "policy": public.validation_floor_policy.reference().model_dump(
                mode="json", by_alias=True
            ),
            "floorState": (
                "independent-fresh-session-replay-controls-ai-floor-satisfied"
                if domain == "ai"
                else "floor-satisfied-independent-fresh-worker-replay"
            ),
            "authorityBoundary": boundary.model_dump(mode="json", by_alias=True),
            "metrics": metrics,
            "requiredMetricCount": sum(
                item.applicability.value == "required"
                for item in public.validation_floor_policy.requirements
            ),
            "notApplicableMetricCount": sum(
                item.applicability.value == "not-applicable"
                for item in public.validation_floor_policy.requirements
            ),
            "satisfactionField": "floorSatisfied" if domain == "ai" else "satisfied",
        }
    return (
        "// Generated by pajin.control_plane.measured_product_web_contract; public metadata only.\n"
        "export const MEASURED_PRODUCT_CONTRACTS = "
        + json.dumps(values, ensure_ascii=False, indent=2, sort_keys=True)
        + ";\n"
    )
