"""Shadow Supervisor contracts and authorities."""

from pajin.supervision.model_binding import (
    SUPERVISOR_MODEL_BINDING_API_VERSION,
    SUPERVISOR_SHADOW_PROPOSAL_DRAFT_API_VERSION,
    SupervisorModelBinding,
    SupervisorModelBindingError,
    SupervisorModelConfiguration,
    SupervisorModelSchemaBinding,
    SupervisorModelSchemaKind,
    SupervisorProviderModelIdentity,
    SupervisorShadowProposalDraft,
    SupervisorShadowProposalKind,
    bind_supervisor_model,
    verify_supervisor_model_binding,
)
from pajin.supervision.proposal_compiler import (
    SUPERVISOR_TYPED_PROPOSAL_API_VERSION,
    SupervisorCompiledProposal,
    SupervisorEscalationProposal,
    SupervisorProposalCompilationPolicy,
    SupervisorProposalCompilerError,
    SupervisorReplanProposal,
    SupervisorStopProposal,
    SupervisorTaskProposal,
    SupervisorTypedProposal,
    compile_supervisor_shadow_proposal,
    registered_supervisor_proposal_compilation_policy,
    verify_supervisor_typed_proposal,
)
from pajin.supervision.snapshot_input import (
    SUPERVISOR_SNAPSHOT_INPUT_API_VERSION,
    SupervisorInputReference,
    SupervisorInputReferenceKind,
    SupervisorModelVisibleText,
    SupervisorSnapshotInput,
    SupervisorSnapshotInputError,
    SupervisorTargetTaint,
    create_supervisor_snapshot_input,
    verify_supervisor_snapshot_input,
)

__all__ = [
    "SUPERVISOR_MODEL_BINDING_API_VERSION",
    "SUPERVISOR_SHADOW_PROPOSAL_DRAFT_API_VERSION",
    "SUPERVISOR_SNAPSHOT_INPUT_API_VERSION",
    "SUPERVISOR_TYPED_PROPOSAL_API_VERSION",
    "SupervisorCompiledProposal",
    "SupervisorEscalationProposal",
    "SupervisorInputReference",
    "SupervisorInputReferenceKind",
    "SupervisorModelBinding",
    "SupervisorModelBindingError",
    "SupervisorModelConfiguration",
    "SupervisorModelSchemaBinding",
    "SupervisorModelSchemaKind",
    "SupervisorModelVisibleText",
    "SupervisorProposalCompilationPolicy",
    "SupervisorProposalCompilerError",
    "SupervisorProviderModelIdentity",
    "SupervisorReplanProposal",
    "SupervisorShadowProposalDraft",
    "SupervisorShadowProposalKind",
    "SupervisorSnapshotInput",
    "SupervisorSnapshotInputError",
    "SupervisorStopProposal",
    "SupervisorTargetTaint",
    "SupervisorTaskProposal",
    "SupervisorTypedProposal",
    "bind_supervisor_model",
    "compile_supervisor_shadow_proposal",
    "create_supervisor_snapshot_input",
    "registered_supervisor_proposal_compilation_policy",
    "verify_supervisor_model_binding",
    "verify_supervisor_snapshot_input",
    "verify_supervisor_typed_proposal",
]
