"""Evidence-bound attack-surface discovery contracts."""

from pajin.discovery.admission import (
    SurfaceAdmissionError,
    SurfaceCandidate,
    TrustedSurfaceAdapter,
    TrustedSurfaceAdmission,
    TrustedSurfaceProducer,
)
from pajin.discovery.models import (
    DISCOVERY_API_VERSION,
    AttackSurface,
    AttackSurfaceSet,
    HTTPSurfaceLocator,
    SurfaceEvidenceReference,
    SurfaceLocator,
    SurfaceObservation,
    ToolInterfaceSurfaceLocator,
    attack_surface,
    attack_surface_set,
    http_surface_locator,
    surface_observation,
    tool_interface_surface_locator,
)
from pajin.discovery.projection import (
    SurfaceProjectionConflict,
    SurfaceProjectionPublication,
    publish_surface_projection,
)
from pajin.discovery.recon import (
    MCPInterfaceSurfaceAdapter,
    RECON_API_VERSION,
    ReconPlanner,
    ReconWaveError,
    ReconWaveOutcome,
    ReconWavePlan,
    RegisteredMCPReconPlanner,
    SingleReconWaveRunner,
)

__all__ = [
    "DISCOVERY_API_VERSION",
    "RECON_API_VERSION",
    "AttackSurface",
    "AttackSurfaceSet",
    "HTTPSurfaceLocator",
    "MCPInterfaceSurfaceAdapter",
    "ReconPlanner",
    "ReconWaveError",
    "ReconWaveOutcome",
    "ReconWavePlan",
    "RegisteredMCPReconPlanner",
    "SurfaceAdmissionError",
    "SurfaceCandidate",
    "SurfaceEvidenceReference",
    "SurfaceLocator",
    "SurfaceObservation",
    "SurfaceProjectionConflict",
    "SurfaceProjectionPublication",
    "SingleReconWaveRunner",
    "ToolInterfaceSurfaceLocator",
    "TrustedSurfaceAdapter",
    "TrustedSurfaceAdmission",
    "TrustedSurfaceProducer",
    "attack_surface",
    "attack_surface_set",
    "http_surface_locator",
    "publish_surface_projection",
    "surface_observation",
    "tool_interface_surface_locator",
]
